version: "3.7"

services:

##################  DATABASE  #########################
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    # volumes:
      # - db-data:/var/lib/postgresql/data/

  angular-frontend:
    image: local/frontend:latest
    build:
      context: ./atouch-frontend
      dockerfile: Dockerfile

  backend-rest:
    image: local/backend-rest:latest
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile

  backend-websocket:
    image: local/backend-websocket:latest
    restart: always
    build:
      context: ./websockets
      dockerfile: Dockerfile

  reverse-proxy:
    restart: always
    image: local/reverse-proxy
    restart: always
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - 80:80

  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080


# volumes:
#   db-data:
